export const categories = ["Tất Cả", "Phim Ảnh", "Trò Chơi", "Âm Nhạc"];

export const mediaData = [
  {
    id: "SƠN TÙNG -MTP",
    title: "COME MY WAY",
    category: "MUSIC",
    genre: "Tâm Lý / Gia Đình",
    rating: 9.5,
    year: 2024,
    duration: "2h 18m",
    tagline: "Mẹ yêu các con bằng cả cuộc đời. Các con yêu mẹ được bao nhiêu?",
    description: "Câu chuyện cảm động về bà Hai, một người mẹ đơn thân tảo tần nuôi nấng 5 người con khôn lớn. Khi bà gặp tai nạn chấn thương chân, một câu hỏi nan giải đặt ra: ai trong số các con sẽ về chăm sóc mẹ khi ai cũng có cuộc sống riêng bận rộn?",
    videoUrl: "https://www.youtube.com/watch?v=SlQR9iu09bQ",
    posterUrl: "https://media-cdn-v2.laodong.vn/storage/newsportal/2026/6/2/1712242/6.jpg",
    backdropUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf-HlVmQVoptP996atf-xuJ1CPDRbiKwKM9Ub35ECt9k31myrCnS4KBays&s=10",
    featured: true,
    trending: true,
    author: "Lý Hải"
  },
  {
    id: "SƠN TÙNG -MTP",
    title: "ĐỪNG LÀM TRÁI TIM ANH ĐAU",
    category: "MUSIC",
    genre: "Tâm Lý / Tình Cảm",
    rating: 8.8,
    year: 2024,
    duration: "2h 11m",
    tagline: "Cái gì cũng có thời hạn, chỉ có tình cảm là không thể tính toán.",
    description: "Bộ phim xoay quanh cuộc đời của Mai, một người phụ nữ mát-xa gần 40 tuổi chịu nhiều định kiến xã hội, vô tình gặp gỡ Dương - một chàng trai trẻ tuổi hào hoa, kém cô nhiều tuổi. Tình yêu nảy nở giữa họ phải đối mặt với muôn vàn sóng gió từ gia đình và quá khứ.",
    videoUrl: "https://www.youtube.com/watch?v=exUpeGMs11M",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgwNNRvKOUdOtM-jZj6eriCm5aXFvOPYT9xGcgef0k-O6Q7Ce7jq5YgCs&s=10",
    backdropUrl: "https://upload.wikimedia.org/wikipedia/vi/e/e5/S%C6%A1n_T%C3%B9ng_M-TP_-_%C4%90%E1%BB%ABng_l%C3%A0m_tr%C3%A1i_tim_anh_%C4%91au.png",
    featured: false,
    trending: true,
    author: "Trấn Thành"
  },
  {
    id: "SƠN TÙNG -MTP",
    title: "CHÚNG TA CỦA HIỆN TẠI",
    category: "MUSIC",
    genre: "Lãng Mạn / Tuổi Trẻ",
    rating: 9.1,
    year: 2019,
    duration: "1h 57m",
    tagline: "Có hai thứ đời người không được bỏ lỡ: chuyến tàu cuối cùng và người yêu bạn thật lòng.",
    description: "Chuyển thể từ truyện dài cùng tên của nhà văn Nguyễn Nhật Ánh, bộ phim tái hiện câu chuyện tình đơn phương đầy tiếc nuối của Ngạn dành cho Hà Lan - cô bạn thanh mai trúc mã có đôi mắt biếc hút hồn, trải qua bao thăng trầm của cuộc đời từ làng Đo Đo đến thành phố.",
    videoUrl: "https://www.youtube.com/watch?v=ITlQ0oU7tDA",
    posterUrl: "https://cdn.eva.vn/upload/4-2020/images/2020-12-21/xon-xao-chung-ta-cua-hien-tai-cua-son-tung-m-tp-la-chuyen-that-ve-ho-tran-noi-tieng-sg-3-1608519924-404-width660height930.jpg",
    backdropUrl: "https://baoquocte.vn/stores/news_dataimages/phamthuan/022021/23/14/in_article/mv-chung-ta-cua-hien-tai-cua-son-tung-mtp-vuong-nghi-an-dao-nhac-cua-nha-san-xuat-anh.jpg?rt=20210223143143",
    featured: true,
    trending: false,
    author: "Victor Vũ"
  },
  {
    id: "SƠN TÙNG -MTP",
    title: "ĐỪNG LÀM TRÁI TIM ANH ĐAU",
    category: "Âm Nhạc",
    genre: "Pop / Tình Cảm",
    rating: 9.4,
    year: 2024,
    duration: "4m 21s",
    tagline: "Đừng làm trái tim anh đau, hãy để anh yêu em thật lòng.",
    description: "Bản hit nhạc Pop ngọt ngào, tươi vui của Sơn Tùng M-TP với giai điệu cực kỳ bắt tai và MV lãng mạn kể về câu chuyện tình yêu dễ thương của một chàng trai si tình dành cho cô gái của đời mình.",
    videoUrl: "https://www.youtube.com/watch?v=abPmZCZZrFA",
    posterUrl: "https://upload.wikimedia.org/wikipedia/vi/e/e5/S%C6%A1n_T%C3%B9ng_M-TP_-_%C4%90%E1%BB%ABng_l%C3%A0m_tr%C3%A1i_tim_anh_%C4%91au.png",
    backdropUrl: "https://upload.wikimedia.org/wikipedia/vi/e/e5/S%C6%A1n_T%C3%B9ng_M-TP_-_%C4%90%E1%BB%ABng_l%C3%A0m_tr%C3%A1i_tim_anh_%C4%91au.png",
    featured: true,
    trending: true,
    author: "Sơn Tùng M-TP"
  },
  {
    id: "tai-uong",
    title: "KHÔNG BUÔNG",
    category: "MUSIC",
    genre: "Kinh Dị / Giải Đố",
    rating: 9.0,
    year: 2025,
    duration: "8 Giờ Chơi",
    tagline: "Cơn ác mộng từ truyền thuyết đô thị Việt Nam.",
    description: "Một trò chơi kinh dị góc nhìn thứ nhất do người Việt sản xuất, lấy bối cảnh một khu chung cư cũ kỹ, u ám tại Sài Gòn đầy rẫy những câu chuyện tâm linh kỳ bí. Người chơi phải tìm cách giải quyết các câu đố rùng rợn và đối mặt với thế lực vô hình.",
    videoUrl: "https://www.youtube.com/watch?v=9UcQ7ddVjoc",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPIh89LTI42G_F9NIeoEyzxPpZXA4sA3wN_EBaJ_JijdL7yzozxVXLIhWP&s=10",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1200",
    featured: false,
    trending: true,
    author: "BeazTek Studio"
  },
  {
    id: "VŨ",
    title: "NHỮNG LỜI HỨA BỎ QUÊN",
    category: "MUSIC",
    genre: "Phiêu Lưu / Nghệ Thuật",
    rating: 9.6,
    year: 2021,
    duration: "4 Giờ Chơi",
    tagline: "Hành trình diệu kỳ tìm lại ký ức bình yên.",
    description: "Hoa là một trò chơi đi cảnh giải đố tuyệt đẹp với đồ họa vẽ tay nghệ thuật lấy cảm hứng từ Studio Ghibli. Bạn sẽ đồng hành cùng cô bé Hoa đi qua những vùng đất thiên nhiên kỳ ảo đầy thơ mộng, lắng nghe những bản nhạc piano du dương đầy cảm xúc.",
    videoUrl: "https://www.youtube.com/watch?v=kOU7a6BzDEk&list=RDkOU7a6BzDEk&start_radio=1",
    posterUrl: "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/cover/3/4/7/4/34745c8f9c8221be92d2c08ac5ee72bc.jpg",
    backdropUrl: "https://cdn2.tuoitre.vn/471584752817336320/2023/12/14/nos7932-17025653279281231311716.jpg",
    featured: false,
    trending: true,
    author: "Skrollcat Studio"
  },
  {
    id: "NGÔ LAN HƯƠNG ",
    title: "CÓ CÔNG MÀI SẮT",
    category: "Âm Nhạc",
    genre: "Pop / R&B",
    rating: 9.3,
    year: 2020,
    duration: "5m 01s",
    tagline: "Liệu tương lai có giữ được lời hứa ngày hôm qua?",
    description: "Bản hit R&B đầy cảm xúc mang phong cách hoài niệm cổ điển kể về một câu chuyện tình yêu đầy lôi cuốn của Sơn Tùng M-TP kết hợp cùng Hải Tú trong MV được đầu tư hoành tráng hàng đầu nhạc Việt.",
    videoUrl: "https://www.youtube.com/watch?v=zWZHnfoVV3w&list=RDGMEMYH9CUrFO7CfLJpaD7UR85wVMzWZHnfoVV3w&start_radio=1",
    posterUrl: "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/cover/a/1/b/5/a1b5107bed7f2b9b27500ffce5cecb81.jpg",
    backdropUrl: "https://i.ytimg.com/vi/5oWAB1-nCz8/maxresdefault.jpg",
    featured: false,
    trending: true,
    author: "Sơn Tùng M-TP"
  },
  {
    id: "loi-nho-den",
    title: "MỘT ĐỜI ",
    category: "Âm Nhạc",
    genre: "Hip Hop / Rap / Indie",
    rating: 9.5,
    year: 2019,
    duration: "4m 28s",
    tagline: "Một lối nhỏ dẫn ta tìm về những bình yên cũ.",
    description: "Bài hát rap mộc mạc mang âm hưởng hoài niệm kết hợp giữa những câu rap đầy suy tư, triết lý của Đen Vâu và giọng hát ngọt ngào của Phương Anh Đào, đưa người nghe vào một cuộc hành trình cảm xúc bình lặng và sâu lắng.",
    videoUrl: "https://www.youtube.com/watch?v=JgTZvDbaTtg&list=RDkOU7a6BzDEk&index=4",
    posterUrl: "https://i.scdn.co/image/ab67616d0000b2732464fa5548d77e5f87ee20cb",
    backdropUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-UhgmMufuv-MGpQ7o99CI6r8jAKWXd6MX_hRrQaN3bE8QIIwpiGjHqMxd&s=10",
    featured: false,
    trending: false,
    author: "Đen Vâu ft. Phương Anh Đào"
  },

];
