export const categories = ["Tất Cả", "Phim Ảnh", "Trò Chơi", "Âm Nhạc"];

export const mediaData = [
  {
    id: "come-my-way",
    title: "COME MY WAY",
    category: "Âm Nhạc",
    genre: "Pop / R&B / Hip Hop",
    rating: 9.5,
    year: 2026,
    duration: "3m 55s",
    tagline: "Sự kết hợp bùng nổ xuyên quốc gia giữa Sơn Tùng M-TP và Tyga.",
    description: "Một siêu phẩm âm nhạc mang âm hưởng Hip Hop và R&B hiện đại, đánh dấu màn bắt tay quốc tế đầy ấn tượng giữa Sơn Tùng M-TP và nam rapper đình đám US-UK Tyga. Bài hát sở hữu giai điệu vô cùng lôi cuốn, thời thượng cùng phần hình ảnh MV chất chơi, phóng khoáng, khẳng định bước tiến mới của nam ca sĩ trên bản đồ âm nhạc thế giới.",
    videoUrl: "https://www.youtube.com/watch?v=SlQR9iu09bQ",
    posterUrl: "https://media-cdn-v2.laodong.vn/storage/newsportal/2026/6/2/1712242/6.jpg",
    backdropUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf-HlVmQVoptP996atf-xuJ1CPDRbiKwKM9Ub35ECt9k31myrCnS4KBays&s=10",
    featured: true,
    trending: true,
    author: "Sơn Tùng M-TP ft. Tyga"
  },
  {
    id: "dung-lam-trai-tim-anh-dau",
    title: "ĐỪNG LÀM TRÁI TIM ANH ĐAU",
    category: "Âm Nhạc",
    genre: "Pop / Ballad",
    rating: 8.8,
    year: 2024,
    duration: "4m 21s",
    tagline: "Đừng làm trái tim anh đau, hãy để anh yêu em thật lòng.",
    description: "Một bản hit nhạc Pop ngọt ngào, tươi vui và ngập tràn năng lượng hạnh phúc của Sơn Tùng M-TP. Với giai điệu bắt tai, ca từ dễ thương cùng MV mang màu sắc lãng mạn, hài hước kể về hành trình si tình của một chàng trai văn phòng, bài hát nhanh chóng chiếm trọn trái tim của hàng triệu khán giả và dẫn đầu các bảng xếp hạng âm nhạc.",
    videoUrl: "https://www.youtube.com/watch?v=exUpeGMs11M",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgwNNRvKOUdOtM-jZj6eriCm5aXFvOPYT9xGcgef0k-O6Q7Ce7jq5YgCs&s=10",
    backdropUrl: "https://upload.wikimedia.org/wikipedia/vi/e/e5/S%C6%A1n_T%C3%B9ng_M-TP_-_%C4%90%E1%BB%ABng_l%C3%A0m_tr%C3%A1i_tim_anh_%C4%91au.png",
    featured: false,
    trending: true,
    author: "Sơn Tùng M-TP"
  },
  {
    id: "chung-ta-cua-hien-tai",
    title: "CHÚNG TA CỦA HIỆN TẠI",
    category: "Âm Nhạc",
    genre: "Pop / R&B / Retro",
    rating: 9.1,
    year: 2020,
    duration: "14m 50s",
    tagline: "Liệu tương lai có giữ được lời hứa ngày hôm qua?",
    description: "Một bản tình ca Pop/R&B mang âm hưởng retro hoài niệm đầy cảm xúc của Sơn Tùng M-TP. MV được xây dựng như một bộ phim điện ảnh ngắn lấy bối cảnh những năm cuối thế kỷ 20, kể về câu chuyện tình yêu đầy lôi cuốn nhưng cũng đẫm nước mắt và tiếc nuối giữa một chàng thiếu gia thuộc thế giới ngầm và một cô gái xinh đẹp, mộc mạc nơi thị trấn nhỏ.",
    videoUrl: "https://www.youtube.com/watch?v=psZ1g9fMfeo",
    posterUrl: "https://cdn.eva.vn/upload/4-2020/images/2020-12-21/xon-xao-chung-ta-cua-hien-tai-cua-son-tung-m-tp-la-chuyen-that-ve-ho-tran-noi-tieng-sg-3-1608519924-404-width660height930.jpg",
    backdropUrl: "https://baoquocte.vn/stores/news_dataimages/phamthuan/022021/23/14/in_article/mv-chung-ta-cua-hien-tai-cua-son-tung-mtp-vuong-nghi-an-dao-nhac-cua-nha-san-xuat-anh.jpg?rt=20210223143143",
    featured: true,
    trending: false,
    author: "Sơn Tùng M-TP"
  },
  {
    id: "SƠN TÙNG -MTP",
    title: "ĐỪNG LÀM TRÁI TIM ANH ĐAU",
    category: "Âm Nhạc",
    genre: "Pop / Tình Cảm",
    rating: 9.4,
    year: 2024,
    duration: "4m 21s",
    tagline: "Đừng làm trái tim anh đau, hãy để anh yêu em thật lòng.",
    description: "Bản hit nhạc Pop ngọt ngào, tươi vui của Sơn Tùng M-TP với giai điệu cực kỳ bắt tai và MV lãng mạn kể về câu chuyện tình yêu dễ thương của một chàng trai si tình dành cho cô gái của đời mình.",
    videoUrl: "https://www.youtube.com/watch?v=abPmZCZZrFA",
    posterUrl: "https://upload.wikimedia.org/wikipedia/vi/e/e5/S%C6%A1n_T%C3%B9ng_M-TP_-_%C4%90%E1%BB%ABng_l%C3%A0m_tr%C3%A1i_tim_anh_%C4%91au.png",
    backdropUrl: "https://upload.wikimedia.org/wikipedia/vi/e/e5/S%C6%A1n_T%C3%B9ng_M-TP_-_%C4%90%E1%BB%ABng_l%C3%A0m_tr%C3%A1i_tim_anh_%C4%91au.png",
    featured: true,
    trending: true,
    author: "Sơn Tùng M-TP"
  },
  {
    id: "khong-buong",
    title: "KHÔNG BUÔNG",
    category: "Trò Chơi",
    genre: "Kinh Dị / Giải Đố / Tâm Linh",
    rating: 9.0,
    year: 2025,
    duration: "8 Giờ Chơi",
    tagline: "Cơn ác mộng từ truyền thuyết đô thị Việt Nam.",
    description: "Một trò chơi kinh dị sinh tồn góc nhìn thứ nhất do người Việt sản xuất, lấy bối cảnh một khu chung cư cũ kỹ, u ám đầy rẫy những hiện tượng tâm linh kỳ bí. Người chơi sẽ phải đối mặt với một thế lực vô hình oán hận bám đuổi dai dẳng không rời. Bằng cách giải quyết các câu đố rùng rợn và lật mở những bí mật đen tối bị chôn giấu, bạn phải tìm cách sống sót và thoát khỏi lời nguyền đáng sợ — đúng như cái tên 'Không Buông'.",
    videoUrl: "https://www.youtube.com/watch?v=9UcQ7ddVjoc",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPIh89LTI42G_F9NIeoEyzxPpZXA4sA3wN_EBaJ_JijdL7yzozxVXLIhWP&s=10",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1200",
    featured: true,
    trending: true,
    author: "BeazTek Studio"
  },
  {
    id: "nhung-loi-hua-bo-quen",
    title: "NHỮNG LỜI HỨA BỎ QUÊN",
    category: "Âm Nhạc",
    genre: "Pop / Ballad / Indie",
    rating: 9.6,
    year: 2023,
    duration: "4m 58s",
    tagline: "Lời hứa năm xưa giờ chỉ còn là những ký ức vụn vỡ.",
    description: "Một bản tình ca đầy da diết và giàu chất tự sự của 'hoàng tử indie' Vũ. kết hợp cùng ban nhạc Hong Kong Dear Jane. Bài hát là nỗi lòng của một người trưởng thành khi nhìn lại mối tình thanh xuân đã qua, tiếc nuối về những lời hẹn ước dở dang chưa kịp thực hiện, tất cả được gói gọn trong những giai điệu Pop Ballad nhẹ nhàng và MV mang màu sắc hoài niệm đầy cảm xúc.",
    videoUrl: "https://www.youtube.com/watch?v=kOU7a6BzDEk",
    posterUrl: "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/cover/3/4/7/4/34745c8f9c8221be92d2c08ac5ee72bc.jpg",
    backdropUrl: "https://cdn2.tuoitre.vn/471584752817336320/2023/12/14/nos7932-17025653279281231311716.jpg",
    featured: true,
    trending: true,
    author: "Vũ. ft. Dear Jane"
  },
  {
    id: "co-cong-mai-sat",
    title: "CÓ CÔNG MÀI SẮT",
    category: "Âm Nhạc",
    genre: "Pop / Modern Folk / V-Pop",
    rating: 9.3,
    year: 2024,
    duration: "4m 03s",
    tagline: "Có công mài sắt, có ngày nên kim... liệu tình yêu có như câu ví?",
    description: "Một ca khúc vô cùng bắt tai và cá tính của Ngô Lan Hương, kết hợp khéo léo giữa chất liệu âm nhạc hiện đại và câu ca dao tục ngữ quen thuộc của Việt Nam. Bài hát mang giai điệu vui tươi, tinh nghịch xen lẫn chút châm biếm, kể về hành trình kiên trì theo đuổi tình yêu của một cô gái nhưng cũng đầy tỉnh táo trước những lời đường mật.",
    videoUrl: "https://www.youtube.com/watch?v=zWZHnfoVV3w",
    posterUrl: "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/cover/a/1/b/5/a1b5107bed7f2b9b27500ffce5cecb81.jpg",
    backdropUrl: "https://i.ytimg.com/vi/5oWAB1-nCz8/maxresdefault.jpg",
    featured: false,
    trending: true,
    author: "Ngô Lan Hương"
  },

  {
    id: "mot-doi",
    title: "MỘT ĐỜI",
    category: "Âm Nhạc",
    genre: "Pop / Ballad / Indie",
    rating: 9.5,
    year: 2024,
    duration: "4m 42s",
    tagline: "Một đời này ta đi tìm kiếm điều gì giữa những muộn phiền?",
    description: "Một ca khúc Indie Pop/Ballad đầy nhẹ nhàng, sâu lắng và mang nhiều tâm sự nằm trong album 'SỐ KHÔNG' của 14 Casper và Bon Nghiêm, kết hợp cùng giọng hát ngọt ngào, giàu cảm xúc của buitruonglinh. Bài hát là những lời chiêm nghiệm đầy bình yên về cuộc sống, tình yêu và những trải nghiệm mà mỗi người đi qua trong suốt một đời.",
    videoUrl: "https://www.youtube.com/watch?v=JgTZvDbaTtg",
    posterUrl: "https://i.scdn.co/image/ab67616d0000b2732464fa5548d77e5f87ee20cb",
    backdropUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-UhgmMufuv-MGpQ7o99CI6r8jAKWXd6MX_hRrQaN3bE8QIIwpiGjHqMxd&s=10",
    featured: false,
    trending: false,
    author: "14 Casper & Bon Nghiêm ft. buitruonglinh"
  },

];
